### ISSUE TITLE
run python mcts.py will raise error

### ISSUE THREAD

**Issue by gitzyong812** [DIRECT-BIT/SRA-MCTS#5]
```
Original exception was:
Traceback (most recent call last):
  File "mcts.py", line 38, in <module>
    task = MCTS_Task(question, model, model, lang='en', use_reflection='common', iteration_limit=2)
  File "SRA-MCTS/MCTS/task.py", line 708, in run
    node, finish, root = MCTS(self)
  File "SRA-MCTS/MCTS/mcts.py", line 247, in MCTS
    root, node, finish = MCTS_search(mcts_task)
  File "SRA-MCTS/MCTS/mcts.py", line 123, in MCTS_search
    flag, node, root = executeRound(root, mcts_task)
  File "SRA-MCTS/MCTS/mcts.py", line 150, in executeRound
    if mcts_task.reward_model_type == 'vm':
  File "SRA-MCTS/MCTS/mcts.py", line 88, in greedyPolicy
    actions = get_next_steps_roll(strs, cur_step, mcts_task)  # str_list
  File "SRA-MCTS/MCTS/mcts.py", line 16, in get_next_steps_roll
    proposal = mcts_task.get_next_step(y, step_n)
TypeError: get_next_step() missing 1 required positional argument: 'history'
```

**Comment by w1z1x0** [comment]
For the function `get_next_steps_roll(y: str, step_n: int, mcts_task)`, This function is used in the rollout phase of MCTS, also known as the simulation phase. The purpose of this phase is to simulate several possible next steps (next_steps) starting from the current state y to evaluate potential outcomes.
Which means this is just a part of simulation instead of the real solution, so may be `history` here is not important, you can change `proposal = mcts_task.get_next_step(y, step_n)` => `proposal = mcts_task.get_next_step(y, step_n,[])`

**Comment by DuanyangYuan** [comment]
> ```
> Original exception was:
> Traceback (most recent call last):
>   File "mcts.py", line 38, in <module>
>     task = MCTS_Task(question, model, model, lang='en', use_reflection='common', iteration_limit=2)
>   File "SRA-MCTS/MCTS/task.py", line 708, in run
>     node, finish, root = MCTS(self)
>   File "SRA-MCTS/MCTS/mcts.py", line 247, in MCTS
>     root, node, finish = MCTS_search(mcts_task)
>   File "SRA-MCTS/MCTS/mcts.py", line 123, in MCTS_search
>     flag, node, root = executeRound(root, mcts_task)
>   File "SRA-MCTS/MCTS/mcts.py", line 150, in executeRound
>     if mcts_task.reward_model_type == 'vm':
>   File "SRA-MCTS/MCTS/mcts.py", line 88, in greedyPolicy
>     actions = get_next_steps_roll(strs, cur_step, mcts_task)  # str_list
>   File "SRA-MCTS/MCTS/mcts.py", line 16, in get_next_steps_roll
>     proposal = mcts_task.get_next_step(y, step_n)
> TypeError: get_next_step() missing 1 required positional argument: 'history'
> ```

请问您出现下面错误了吗：ERROR: /home/bxu/EXP/LLaMA-Factory is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
